site_name: Linx Docs
repo_url: https://github.com/Linx-ESP/LinxESP-Docs
repo_name: Github / Linx-ESP
edit_uri: ""
theme:
  language: es
  logo: assets/linx.png
  favicon: assets/linx.png
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: red
      accent: blue
      toggle:
        icon: material/weather-sunny-off
        name: Cambiar a modo claro
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.top
    - navigation.indexes
    - header.autohide
#    - toc.integrate #Navegación dentro del archivo. Disable = columna a la derecha

extra_css:
  - assets/stylesheets/extra.css

extra:
#  alternate:
#  - name: Español (Original)
#    link: /
#    lang: es 
##  - name: English (WIP)
##    link: /en/
#    lang: en 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Linx-ESP
#  analytics:
#    provider: google
#    property: G-Q94MVTWP0F
#  extra:
#  consent:
#    title: Cookie consent
#    description: 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
#    cookies:
#      analytics:
#        name: Google Analytics
#      github:
#        name: Github

plugins:
  - search
#  - tags:
#      tags_file: tags.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.snippets:
      auto_append:
        - assets/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - footnotes
  - def_list
  - md_in_html
  - attr_list
  - meta
  - abbr

